require('bootstrap');
require('owl.carousel');
require('select2');
require('bootstrap-datepicker');
require('jquery-aniview');
require('bootstrap-datepicker/js/locales/bootstrap-datepicker.sk');
require('daterangepicker');
window.Cropper = require('cropperjs');
require('jquery-cropper/src');
require('./animatescroll.js');
require('./lightbox.min');
require('./awselect');
require('./script.js');
import bsCustomFileInput from 'bs-custom-file-input';
